name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: id_rsa # Default is id_rsa
          known_hosts: "just-a-placeholder-so-we-can-use-StrictHostKeyChecking-no"

      - name: Deploy and Restart
        run: |
          ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ secrets.DROPLET_IP_ADDRESS }} "
            cd /var/www/passport-buddy && \
            git pull origin main && \
            npm install && \
            cd frontend && \
            npm install && \
            npm run build && \
            cd .. && \
            pm2 restart passport-buddy || pm2 start server.js --name passport-buddy
          "